# ========== TRANSLATIONS DATABASE ==========
translations = {
    "English": {
        "navigation": "📚 Navigation",
        "select_module": "Select Module",
        "home": "🏠 Home",
        "reynolds": "📊 Reynolds Number",
        "heat_transfer": "🔥 Heat Transfer",
        "pressure_drop": "📉 Pressure Drop",
        "unit_converter": "🔄 Unit Converter",
        "heat_exchanger": "🌡️ Heat Exchanger",
        "formulas": "📚 Formulas",
        "tip": "💡 Tip: Select a module to get started",
        "language": "🌐 Language"
    },
    "Urdu": {
        "navigation": "📚 رہنمائی",
        "select_module": "ماڈیول منتخب کریں",
        "home": "🏠 ہوم",
        "reynolds": "📊 رینالڈز نمبر",
        "heat_transfer": "🔥 حرارت کی منتقلی",
        "pressure_drop": "📉 پریشر ڈراپ",
        "unit_converter": "🔄 یونٹ کنورٹر",
        "heat_exchanger": "🌡️ ہیٹ ایکسچینجر",
        "formulas": "📚 فارمولے",
        "tip": "💡 نوکری: شروع کرنے کے لیے کوئی ماڈیول منتخب کریں",
        "language": "🌐 زبان"
    },
    "Hindi": {
        "navigation": "📚 नेविगेशन",
        "select_module": "मॉड्यूल चुनें",
        "home": "🏠 होम",
        "reynolds": "📊 रेनॉल्ड्स संख्या",
        "heat_transfer": "🔥 ऊष्मा स्थानांतरण",
        "pressure_drop": "📉 दबाव में गिरावट",
        "unit_converter": "🔄 यूनिट कनवर्टर",
        "heat_exchanger": "🌡️ हीट एक्सचेंजर",
        "formulas": "📚 सूत्र",
        "tip": "💡 टिप: शुरू करने के लिए कोई मॉड्यूल चुनें",
        "language": "🌐 भाषा"
    },
    "Arabic": {
        "navigation": "📚 التنقل",
        "select_module": "اختر الوحدة",
        "home": "🏠 الرئيسية",
        "reynolds": "📊 رقم رينولدز",
        "heat_transfer": "🔥 انتقال الحرارة",
        "pressure_drop": "📉 انخفاض الضغط",
        "unit_converter": "🔄 محول الوحدات",
        "heat_exchanger": "🌡️ مبادل حراري",
        "formulas": "📚 الصيغ",
        "tip": "💡 نصيحة: اختر وحدة للبدء",
        "language": "🌐 اللغة"
    },
    "Spanish": {
        "navigation": "📚 Navegación",
        "select_module": "Seleccionar Módulo",
        "home": "🏠 Inicio",
        "reynolds": "📊 Número de Reynolds",
        "heat_transfer": "🔥 Transferencia de Calor",
        "pressure_drop": "📉 Caída de Presión",
        "unit_converter": "🔄 Convertidor de Unidades",
        "heat_exchanger": "🌡️ Intercambiador de Calor",
        "formulas": "📚 Fórmulas",
        "tip": "💡 Consejo: Seleccione un módulo para comenzar",
        "language": "🌐 Idioma"
    },
    "French": {
        "navigation": "📚 Navigation",
        "select_module": "Sélectionner un Module",
        "home": "🏠 Accueil",
        "reynolds": "📊 Nombre de Reynolds",
        "heat_transfer": "🔥 Transfert de Chaleur",
        "pressure_drop": "📉 Chute de Pression",
        "unit_converter": "🔄 Convertisseur d'Unités",
        "heat_exchanger": "🌡️ Échangeur de Chaleur",
        "formulas": "📚 Formules",
        "tip": "💡 Conseil: Sélectionnez un module pour commencer",
        "language": "🌐 Langue"
    },
    "German": {
        "navigation": "📚 Navigation",
        "select_module": "Modul auswählen",
        "home": "🏠 Startseite",
        "reynolds": "📊 Reynolds-Zahl",
        "heat_transfer": "🔥 Wärmeübertragung",
        "pressure_drop": "📉 Druckverlust",
        "unit_converter": "🔄 Einheitenumrechner",
        "heat_exchanger": "🌡️ Wärmetauscher",
        "formulas": "📚 Formeln",
        "tip": "💡 Tipp: Wählen Sie ein Modul aus",
        "language": "🌐 Sprache"
    },
    "Chinese": {
        "navigation": "📚 导航",
        "select_module": "选择模块",
        "home": "🏠 首页",
        "reynolds": "📊 雷诺数",
        "heat_transfer": "🔥 传热",
        "pressure_drop": "📉 压降",
        "unit_converter": "🔄 单位转换器",
        "heat_exchanger": "🌡️ 换热器",
        "formulas": "📚 公式",
        "tip": "💡 提示：选择一个模块开始",
        "language": "🌐 语言"
    },
    "Turkish": {
        "navigation": "📚 Navigasyon",
        "select_module": "Modül Seçin",
        "home": "🏠 Ana Sayfa",
        "reynolds": "📊 Reynolds Sayısı",
        "heat_transfer": "🔥 Isı Transferi",
        "pressure_drop": "📉 Basınç Düşüşü",
        "unit_converter": "🔄 Birim Dönüştürücü",
        "heat_exchanger": "🌡️ Isı Değiştirici",
        "formulas": "📚 Formüller",
        "tip": "💡 İpucu: Başlamak için bir modül seçin",
        "language": "🌐 Dil"
    },
    "Russian": {
        "navigation": "📚 Навигация",
        "select_module": "Выберите модуль",
        "home": "🏠 Главная",
        "reynolds": "📊 Число Рейнольдса",
        "heat_transfer": "🔥 Теплопередача",
        "pressure_drop": "📉 Перепад давления",
        "unit_converter": "🔄 Конвертер единиц",
        "heat_exchanger": "🌡️ Теплообменник",
        "formulas": "📚 Формулы",
        "tip": "💡 Совет: Выберите модуль для начала",
        "language": "🌐 Язык"
    }
}
